apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: namespace-configmap-composition
spec:
  mode: Resources
  compositeTypeRef:
    apiVersion: platform.crossplane.io/v1alpha1
    kind: XNamespaceConfigMap
  resources:
    - name: namespace-object
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: namespace-object
        spec:
          providerConfigRef:
            name: default
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: placeholder
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.name
    - name: configmap-object
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: configmap-object
        spec:
          providerConfigRef:
            name: default
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: placeholder
                namespace: placeholder
              data: {}
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.configMapName
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.configMapData
          toFieldPath: spec.forProvider.manifest.data
