apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: namespace-configmap-composition

spec:
  compositeTypeRef:
    apiVersion: platform.crossplane.io/v1alpha1
    kind: XNamespaceConfigMap

  mode: Pipeline

  pipeline:

  - step: patch-and-transform

    functionRef:
      name: function-patch-and-transform

    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources

      resources:

      ########################################################
      # Namespace
      ########################################################

      - name: namespace-object

        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object

          spec:
            providerConfigRef:
              name: default

            forProvider:
              manifest:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: placeholder

        patches:

        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.name

      ########################################################
      # ConfigMap
      ########################################################

      - name: configmap-object

        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object

          spec:
            providerConfigRef:
              name: default

            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap

                metadata:
                  name: placeholder
                  namespace: placeholder

                data: {}

        patches:

        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.namespace

        - type: FromCompositeFieldPath
          fromFieldPath: spec.configMapName
          toFieldPath: spec.forProvider.manifest.metadata.name

        - type: FromCompositeFieldPath
          fromFieldPath: spec.configMapData
          toFieldPath: spec.forProvider.manifest.data