apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnamespaceconfigmaps.platform.crossplane.io
spec:
  group: platform.crossplane.io
  names:
    kind: XNamespaceConfigMap
    plural: xnamespaceconfigmaps
  claimNames:
    kind: NamespaceConfigMap
    plural: namespaceconfigmaps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                configMapName:
                  type: string
                configMapData:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - namespace
                - configMapName
