apiVersion: platform.crossplane.io/v1alpha1
kind: NamespaceConfigMap

metadata:
  name: demo-platform-v2
  namespace: argocd

spec:

  namespace: platform-demo-section

  configMapName: platform-demo-config-section

  configMapData:

    message: "Hello from my first Crossplane Composition"

    owner: "crossplane"

    environment: "lab"